#define JUDGE_AC 0
#define JUDGE_WA 1
#define JUDGE_TLE 2
#define JUDGE_MLE 3
#define JUDGE_RF 4
#define JUDGE_RE 5
#define JUDGE_CE 6
#define JUDGE_ERR 7

#define JUDGE_DB_STATUSMAX 1024
#define JUDGE_DB_SCOREMAX 1024
#define JUDGE_DB_MAXSCOREMAX 1024
#define JUDGE_DB_RUNTIMEMAX 1024
#define JUDGE_DB_PEAKMEMMAX 1024
